lang:
  en-US: en
  zh-CN: zhs
  zh-HK: zht
name:
  en-US: English
  zh-CN: 简体中文
  zh-HK: 繁體中文
nav/home:
  en-US: Home
  zh-CN: 首页
nav/roadmap:
  en-US: Roadmap
  zh-CN: 路线图
nav/learn:
  en-US: Learn
  zh-CN: 了解
nav/overview:
  en-US: Overview
  zh-CN: 概览
nav/resources:
  en-US: Resources
  zh-CN: 资源
nav/developers:
  en-US: Developers
  zh-CN: 开发者
nav/docs:
  en-US: Docs
  zh-CN: 文档
nav/team:
  en-US: Team
  zh-CN: 团队
nav/blog:
  en-US: Blog
  zh-CN: 博客
footer/updates:
  en-US: Updates
  zh-CN: 订阅更新
footer/updateblurb:
  en-US: We send out periodic emails with what&rsquo;s new for Themelio.
  zh-CN: 我们会定期发送邮件，通知您 Themelio 相关的最新消息。
footer/noshare:
  en-US: We never share your email with other people.
  zh-CN: 我们从不会将您的邮箱地址泄露给他人。
footer/subscribe:
  en-US: Subscribe
  zh-CN: 订阅
footer/partners:
  en-US: Partners
  zh-CN: 合作伙伴

overview/themelio-decoupled:
  en-US: |
    <h3>Themelio&rsquo;s decoupled architecture</h3>
    <ul>
        <li>Separated from applications by flexible mid-level protocols</li>
        <li>Applications and protocols can evolve without changing layer-1 blockchain</li>
        <li>Powerful enough to build layer-2 protocols that inherit the blockchain's security</li>
        <li>Governance-free, immutable blockchain that needs no change</li>
    </ul>
  zh-CN: |
    <h3>Themelio 的解耦架构</h3>
    <ul>
        <li>透过插入灵活的中间层协议，让区块链与应用程序分隔开来</li>
        <Li>应用程序与中间层协议可在不改变第 1 层区块链底层协议的前提下发展演化</li>
        <Li>足够强大以打造第 2 层协议，同时继承区块链底层的安全性</li>
        <li>无需治理，不可变区块链底层无需任何更改</li>
    </ul>
overview/robust-endogenous-trust:
  en-US: >
    <h3>Robust endogenous trust</h3>

    <p>Blockchains' most distinctive feature is <b>endogenous trust</b>:
    security guaranteed by the protocol, not by its participants. Yet existing
    blockchains don&rsquo;t ensure endogenous trust. Tightly coupled with
    applications, they are forced to change with application needs. And we are
    forced to trust whoever decides the changes.</p>

    <p>So Themelio rejects the &ldquo;world computer&rdquo; paradigm that
    directly interfaces with apps. We focus on providing an <a
    href="https://docs.themelio.org/basic-concepts/01-endogenous-trust/">immutable
    foundation that never needs trust-damaging protocol changes</a>.</p>
  zh-CN: >
    <h3>坚韧的内生信任</h3>

    <p>区块链最显著的特性便是<b>内生信任</b>&mdash;&mdash;安全性由协议而非参与方来提供保障。但是现存的区块链并不能确保内生信任。由于与应用程序紧密耦合，当下的区块链不得不跟随应用程序的需求变化而做出更改。而我们则被迫去信任这些能够对更改做决策的人。</p>

    <p>因此，Themelio 拒绝采用「世界计算机」这种直接与应用对接的范式。我们旨在提供一种<a
    href="https://docs.themelio.org/basic-concepts/01-endogenous-trust/">不可变的信任底层，该底层永远不会需要进行有损信任的协议更改</a>。</p>
overview/smart-coins:
  en-US: >
    <h3>Covenant-powered smart coins</h3>

    <p>Most general-purpose blockchains use an &ldquo;account-based&rdquo;
    ledger containing accounts with balances and storage. But this tightly
    couples apps with the blockchain and introduces opportunities for
    security-shattering contract bugs, undermining endogenous trust. </p>

    <p>Instead, Themelio uses a more elegant model perfect for a fundamental
    trust layer &mdash; <a
    href="https://docs.themelio.org/basic-concepts/02-state/">Bitcoin's
    &ldquo;coin-based&rdquo; model, augmented with rich scripting and thin
    clients.</a></p>
  zh-CN: >
    <h3>由契约驱动的智能 UTXO</h3>

    <p>大多数通用区块链都采用了一种「基于账户」的模型，这种模型有一个包含所有账户的账户余额和存储的分类账。但这将应用与区块链紧密地耦合在一起，并为有损安全的合约漏洞带来了机会，从而破坏了内生信任。
    </p>

    <p>正因如此，Themelio 采用了一种对于基础信任层来说更为优雅的模型&mdash;&mdash;<a
    href="https://docs.themelio.org/basic-concepts/02-state/">比特币的基于 UTXO
    的模型，并透过富脚本与瘦客户端为其提供功能增强。</a></p>
overview/collusion-resistant:
  en-US: >
    <h3>Collusion-resistant consensus game</h3>

    <p>Even without protocol changes, endogenous trust in any blockchain relies
    on its <b>consensus game</b> that incentivizes correct behavior. But
    blockchains today often design their consensus games on shaky security
    assumptions and patch up failures by violating endogenous trust.</p>

    <p>Themelio's innovative proof-of-stake system, Synkletos, is designed to <a
    href="https://docs.themelio.org/basic-concepts/03-consensus/">maximize
    long-term safety even in the presence of unlimited collusion</a>.</p>
  zh-CN: >
    <h3>防串通的共识博弈</h3>

    <p>即便没有协议上的更改，区块链的内生信任还需要仰赖能够激励正确行为的<b>共识博弈</b>。但是当下的区块链往往会根据不稳健的安全假设来设计共识博弈，并透过违反内生信任的做法在博弈失败时予以修补。</p> 

    <p>Themelio 新颖的权益证明共识机制 Synkletos 从设计上便保障了<a
    href="https://docs.themelio.org/basic-concepts/03-consensus/">最大化长期安全性，即便是在面临无限串通的前提下也仍可安全无虞</a>。</p>
overview/non-fiat-stablecoin:
  en-US: >
    <h3>World&rsquo;s first non-fiat stablecoin</h3>

    <p>Themelio’s base currency, Mel, is a new asset class that finally delivers
    on crypto&rsquo;s promise of sound decentralized money. <a
    href="https://docs.themelio.org/basic-concepts/04-melmint/">Melmint, a fully
    trustless, oracle-free issuance mechanism</a>, stabilizes Mel's value
    against an index representing the time cost of sequential computation.</p>

    <p>Mel has no ties to any fiat currency and stability beyond any
    conventional cryptocurrency. It is a fundamental breakthrough in money.</p>
  zh-CN: >
    <h3>世上首款不与法币挂钩的稳定币</h3>

    <p>Themelio 的基础货币 MEL 是一种全新的资产类别，它终于实现了加密货币所作出的「健全的去中心化货币」的承诺。<a
    href="https://docs.themelio.org/basic-concepts/04-melmint/">Melmint</a>
    是一种完全去信任、免预言机的发行机制，它将 MEL 的价值稳定在一个挂钩于顺序计算时间成本的指数上。</p> 

    <p>MEL 与任何法币都没有丝毫牵扯，但其稳定性却超越既往任何传统的加密货币。它是货币史上的一次根本性突破。</p>
overview/join-our-testnet:
  en-US: >
    <h2>Join our testnet</h2>

    <p class="text--lead">Test out the Themelio network and get mainnet rewards
    by participating in testnet contests.</p>

    <a href="" class="btn btn-outline-dark btn-lg">Testnet portal</a>
  zh-CN: |
    <h2>加入我们的 testnet</h2>
    <p class="text--lead">参与 testnet 比赛，帮助我们测试 Themelio 的网络并获得 mainnet 奖励。</p>
    <a href="" class="btn btn-outline-dark btn-lg">Testnet 门户</a>
overview/knowledge-base:
  en-US: >
    <h2>Knowledge base</h2>

    <p class="text--lead">All the resources you need to learn more about
    Themelio.</p>

    <a href="https://docs.themelio.org/" class="btn btn-outline-dark
    btn-lg">Read now</a>
  zh-CN: >
    <h2>知识库</h2>

    <p class="text--lead">您用来了解 Themelio 的全部资源。</p>

    <a href="https://docs.themelio.org/" class="btn btn-outline-dark
    btn-lg">开始阅读</a>
roadmap/phases:
  en-US: >-
    <h1>Phases of development</h1> <p class="text--lead"> Themelio has four
    phases of development. </p> <p class="text--lead"> Our first step was to
    launch a <b>public alphanet</b> by the end of 2020. This gives us a
    proof-of-concept to tinker with that nevertheless has a degree of public
    participation. At this point, development is highly "agile" and prioritizes
    flexibility over stability. </p> <p class="text--lead"> In 2021, we launched
    a public <b>betanet</b>. This is a fully peer-to-peer blockchain network
    with a consistent, brand-new history, albeit with periodic hard forks and
    centralized governance. The betanet will let us experiment with tweaking and
    optimizing the protocol for real mass usage as well as gain wider usage in
    "serious" applications. In the betanet, history consistency is guaranteed,
    while consensus is gradually decentralized. Consensus-critical protocol
    updates ("hard forks") will happen, though with decreasing frequency. </p>
    <p class="text--lead">Later into the betanet period, we will also launch
    <b>token bridge contracts</b> between Themelio and Ethereum. These contracts
    will allow Themelio tokens like the mel and sym to be traded in the Ethereum
    DeFi ecosystem as ERC-20 tokens, furthering the potential of financial
    instruments based on an endogenous stablecoin. This will also let our main
    cryptocurrency, the mel, to start trading on major decentralized
    cryptocurrency exchanges, such as Uniswap.</p> <p class="text--lead">
    Finally, we plan our <b>stable release</b> some time in 2023-2024. This will
    permanently freeze the protocol specification, while permitting no
    consensus-critical updates unless to fix critical vulnerabilities. The
    betanet will shut down, with its history being entirely inherited. </p>
  zh-CN: >-
    <h1>研发的各个阶段</h1> <p class="text--lead"> Themelio 的研发有四个阶段。 </p> <p
    class="text--lead"> 我们所迈出的第一步是在 2020 年年底前上线了一个<b>公共的 alphanet</b>. 我们将这个
    alphanet 作为一种「概念验证」(PoC)
    去试运营，在对其进行缝缝补补的同时，也实现了一定程度的公众参与。在这一时段，我们的开发是高度「敏捷」的，并且优先考虑灵活性而非稳定性。 </p> <p
    class="text--lead"> 2021 年，我们上线了公共的 <b>betanet</b>.
    这是一个完整的点对点区块链网络，有着一致、全新的历史记录（尽管仍在进行着周期性硬分叉以及中心化治理）。betanet
    让我们可以试验性地对协议进行一些小的修改与优化，使其可以应对真正的大规模使用，以便能够在「严肃」应用程序中得到更广泛的运用。在 betanet
    阶段，历史记录的一致性将得到保障，共识机制在这一阶段将逐渐去中心化。对共识机制至关重要的协议更新（「硬分叉」）仍会发生，但频率会降低。 </p> <p
    class="text--lead">随着 betanet 阶段的深入，我们还会推出 Themelio
    与以太坊之间的<b>代币桥接合约</b>。合约将使 Themelio 的代币（如 MEL 以及 SYM ）得以在以太坊 DeFi 生态系统中以
    ERC-20 代币的形式进行交易，进一步激发其作为内生信任稳定币的金融工具的潜力。这也将使我们的主要加密货币 MEL
    得以开始在几大去中心化加密货币交易所（如 Uniswap）上进行交易。</p> <p class="text--lead"> 最后，我们计划于
    2023-2024 年发布<b>稳定版本</b>。这将永久冻结协议规范，不允许任何关键性的共识更新（除非是为了修复严重的漏洞）。betanet
    将关闭，但其历史将获得完整继承。 </p>
roadmap/past-and-future:
  en-US: >-
    <h2>The past and future of Themelio</h2> <p class="text--lead"> Let's look
    at a timeline of our work related to Themelio. </p>
  zh-CN: >-
    <h2>Themelio 的过去和未来</h2> <p class="text--lead"> 以下为我们团队与 Themelio 项目有关的时间线。
    </p>
roadmap/timeline:
  en-US: >-
    <div class="row mb-3"> <div class="col-3 text-right text-muted">
    <i>circa</i>&nbsp;&nbsp;<b class="font-weight-bold">2014</b> </div> <div
    class="col text-muted"> We begin our long-time obsession over trustless,
    decentralized systems. </div> </div> <div class="row mb-3"> <div
    class="col-3 text-right text-muted"> <i>circa</i>&nbsp;&nbsp;<b
    class="font-weight-bold">2015</b> </div> <div class="col text-muted"> We
    realize that traditional decentralized systems, like DHTs or web-of-trust
    PKIs, miss something critical &mdash; a root of trust. We start
    investigating non-centralized roots of trust, like Certificate Transparency
    and blockchains. </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-muted"> <b class="font-weight-bold">2016</b> </div> <div
    class="col text-muted"> We start research on creating Bitforest, a securely
    decentralized PKI initially based on the Bitcoin blockchain. </div> </div>
    <div class="row mb-3"> <div class="col-3 text-right text-muted"> <b
    class="font-weight-bold">2017</b> </div> <div class="col"> <span
    class="text-muted">We finish </span><span
    class="text--normweight">Bitforest</span>, <span class="text-muted">but in
    the process we realize that existing blockchains are seriously inadequate to
    service as a root of trust for even a basic application like a PKI.</span>
    <span class="text--normweight">Work on Themelio starts.</span> </div> </div>
    <div class="row mb-3"> <div class="col-3 text-right text-muted"> <b
    class="font-weight-bold">2019</b> </div> <div class="col"> <span
    class="text-muted">Our work is almost entirely on Themelio.</span> <span
    class="text--normweight">Themelio's focus shifts from simply advancing the
    state of the art to a paradigm shift in layering.</span> </div> </div> <div
    class="row mb-3 text--normweight"> <div class="col-3 text-right text-muted">
    Q1&nbsp;&nbsp;<b class="font-weight-bold">2019</b> </div> <div class="col">
    First successful test of a prototype client and network </div> </div> <div
    class="row mb-3 text--normweight"> <div class="col-3 text-right text-muted">
    Q2&nbsp;&nbsp;<b class="font-weight-bold">2019</b> </div> <div class="col">
    Website launch </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-muted text--normweight"> Q3&nbsp;&nbsp;<b
    class="font-weight-bold">2020</b> </div> <div class="col"> <b>Public launch
    of a non-persistent "alphanet".</b> From this point on, you'll be able to do
    things like send around mels and deploy apps, albeit on a centralized
    network that may get reset from time to time. The protocol will generally
    freeze during this testing period. </div> </div> <div class="row mb-3"> <div
    class="col-3 text-right text-secondary text--normweight"> Q2&nbsp;&nbsp;<b
    class="font-weight-bold">2021</b> </div> <div class="col"> <b>Public
    "betanet" launch.</b> Unlike the alphanet, the betanet will have persistent
    history. Although "hard-fork" updates will still happen, assets on the
    betanet will be durable and consensus will be gradually decentralized.
    </div> </div> <div class="row mb-3"> <div class="col text-center"> <i
    class="text-muted">you are here</i> </div> </div> <div class="row mb-3">
    <div class="col-3 text-right text-secondary text--normweight">
    Q3-Q4&nbsp;&nbsp;<b class="font-weight-bold">2022</b> </div> <div
    class="col"> <b>Token launch and betanet refinement.</b> Both mels
    (currency) and syms (consensus stakes) on the betanet will be distributed
    through a combination of airdrops and DEX-based token sales. We will also
    use this time to thoroughly audit the protocol, fixing any problems through
    protocol updates, in preparation for the release launch. </div> </div> <div
    class="row mb-3"> <div class="col-3 text-right text-secondary
    text--normweight"> <b class="font-weight-bold">2023-2024</b> </div> <div
    class="col"> <b>Final launch of the Themelio blockchain.</b> Hard forks in
    the blockchains are thereafter forbidden except to fix security
    vulnerabilities. </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-primary text--normweight"> <i class="font-weight-bold">and
    beyond...</i> </div> <div class="col"> <b>Finishing Themelio is just the end
    of the beginning.</b> Themelio is purposefully designed to be simple, but
    that also means pushing complexity to supporting layer-2 protocols. Themelio
    Labs's focus will shift to developing a vibrant and flexible protocol stack,
    with Themelio-rooted security, for building both peer-to-peer and
    server-client networked apps. Of course, that's also where much of the money
    raised from selling syms will be going. </div> </div>
  zh-CN: >-
    <div class="row mb-3"> <div class="col-3 text-right text-muted">
    <i>约</i>&nbsp;&nbsp;<b class="font-weight-bold">2014</b> </div> <div
    class="col text-muted"> 我们开始对去信任、去中心化系统感兴趣，并进而长期痴迷其中。 </div> </div> <div
    class="row mb-3"> <div class="col-3 text-right text-muted">
    <i>约</i>&nbsp;&nbsp;<b class="font-weight-bold">2015</b> </div> <div
    class="col text-muted"> 我们意识到，传统的去中心化系统&mdash;&mdash;如分布式散列表 (DHT) 或信任网
    (WoT) 公钥基础设施
    (PKI)&mdash;&mdash;都缺失了一样关键的东西：信任根。于是开始研究非中心化的信任根，比如「证书透明度」(Certificate
    Transparency) 以及区块链。 </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-muted"> <b class="font-weight-bold">2016</b> </div> <div
    class="col text-muted"> 我们开始研究创建 Bitforest&mdash;&mdash;一个安全去中心化的
    PKI（最初基于比特币区块链）。 </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-muted"> <b class="font-weight-bold">2017</b> </div> <div
    class="col"> <span class="text-muted">我们完成了 </span><span
    class="text--normweight">Bitforest</span>. <span
    class="text-muted">但在过程中，我们意识到，现有的区块链严重不足以充当哪怕是最基本的应用程序（如
    PKI）的信任根。</span><span class="text--normweight">因此，研发 Themelio
    的工作便从此开始。</span> </div> </div> <div class="row mb-3"> <div class="col-3
    text-right text-muted"> <b class="font-weight-bold">2019</b> </div> <div
    class="col"> <span class="text-muted">我们几乎把全部精力都投入到了 Themelio 上。</span><span
    class="text--normweight">起初，Themelio
    的重点在于简单地推动最先进技术更臻至美，但后来逐渐转移到了对协议分层的范式转变上。</span> </div> </div> <div
    class="row mb-3 text--normweight"> <div class="col-3 text-right text-muted">
    Q1&nbsp;&nbsp;<b class="font-weight-bold">2019</b> </div> <div class="col">
    客户端原型与网络的首次成功测试 </div> </div> <div class="row mb-3 text--normweight"> <div
    class="col-3 text-right text-muted"> Q2&nbsp;&nbsp;<b
    class="font-weight-bold">2019</b> </div> <div class="col"> 网站上线 </div>
    </div> <div class="row mb-3"> <div class="col-3 text-right text-muted
    text--normweight"> Q3&nbsp;&nbsp;<b class="font-weight-bold">2020</b> </div>
    <div class="col"> <b>公开上线非持久的 &lsquo;alphanet&rsquo;.</b>
    自这一刻起，用户可以开始做一些事情了，比如发送 MEL
    或者部署应用（尽管这些操作仍是在一个会不时重置的集中化网络上完成的）。在这一测试阶段，协议通常是冻结的。 </div> </div> <div
    class="row mb-3"> <div class="col-3 text-right text-secondary
    text--normweight"> Q2&nbsp;&nbsp;<b class="font-weight-bold">2021</b> </div>
    <div class="col"> <b>公共的 &lsquo;betanet&rsquo; 上线。</b> 与 alphanet
    不同的是，betanet 将具有持久的历史记录。尽管「硬分叉」式更新仍会发生，但 betanet 上的资产将是持久的，共识机制也将逐渐去中心化。
    </div> </div> <div class="row mb-3"> <div class="col text-center"> <i
    class="text-muted">目前进展</i> </div> </div> <div class="row mb-3"> <div
    class="col-3 text-right text-secondary text--normweight">
    Q3-Q4&nbsp;&nbsp;<b class="font-weight-bold">2022</b> </div> <div
    class="col"> <b>推出代币，完善 betanet.</b> betanet 上的 MEL （货币）和 SYM
    （共识抵押）二者均将透过空投和基于 DEX
    的代币销售两种方式的组合来进行分发。我们也将借此时机彻底审核协议，透过协议更新修复任何存在的问题，以为未来的正式发布做准备。 </div> </div>
    <div class="row mb-3"> <div class="col-3 text-right text-secondary
    text--normweight"> <b class="font-weight-bold">2023-2024</b> </div> <div
    class="col"> <b>正式发布 Themelio 区块链。</b>从此以后，除修复安全漏洞外，区块链上的硬分叉将被禁止。 </div>
    </div> <div class="row mb-3"> <div class="col-3 text-right text-primary
    text--normweight"> <i class="font-weight-bold">未来……</i> </div> <div
    class="col"> <b>完成 Themelio 仅仅是开端的结束。</b>Themelio
    特意设计得很简单，但这就意味着，更多复杂的内容被推到了对第 2 层协议的支持上。Themelio Lab
    下一步的重心将转移到研发一个充满生机且灵活的协议栈上，它将具有根植于 Themelio
    的安全性，可用于构建点对点以及服务器－客户端应用。当然，这也将是出售 Sym 筹来的大部分资金的用途所在。 </div> </div>
