[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[redirects]]
  from = "/"
  to = "https://melproject.org"
  status = 301
  force = true

[[redirects]]
  from = "/en/*"
  to = "https://melproject.org"
  status = 301
  force = true
